let data=[];const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){try{const r=await fetch('AKC_FuerzaFIG.xlsx?'+Date.now());if(!r.ok)throw Error('No se encontró AKC_FuerzaFIG.xlsx');const wb=XLSX.read(await r.arrayBuffer(),{type:'array'});data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});home()}catch(e){app.innerHTML=`<p>No se pudo cargar Fuerza FIG: ${esc(e.message)}</p>`}}
function home(){app.innerHTML=`<h2>Sesiones</h2><div class="days">${[...new Set(data.map(x=>x.Dia).filter(Boolean))].map(d=>`<button class="tile" onclick="day('${esc(d)}')"><b>${esc(d)}</b><small>Ver ejercicios programados</small></button>`).join('')}</div>`}
function day(d){const items=data.filter(x=>x.Dia===d);const seg=[...new Set(items.map(x=>x.Segmento).filter(Boolean))];app.innerHTML=`<button class="back" onclick="home()">← Volver</button><h2>${esc(d)}</h2><div class="segments">${seg.map(s=>`<button class="tile" onclick="list('${esc(d)}','${esc(s)}')"><b>${esc(s)}</b><small>${items.filter(x=>x.Segmento===s).length} ejercicios</small></button>`).join('')}</div>`}
function list(d,s){const items=data.filter(x=>x.Dia===d&&x.Segmento===s);app.innerHTML=`<button class="back" onclick="day('${esc(d)}')">← Volver</button><h2>${esc(d)} · ${esc(s)}</h2><div class="cards">${items.map((x,i)=>`<button class="exercise" onclick="video('${encodeURIComponent(x.Link||'')}','${encodeURIComponent(x.Ejercicio||'')}')"><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(x.Ejercicio)}</strong><small>${esc(x.Tipo||'Fuerza FIG')}</small></span><span class="play">▶</span></button>`).join('')}</div>`}
function video(raw,name){const url=decodeURIComponent(raw);app.innerHTML=`<button class="back" onclick="history.back()">← Volver</button><h2>${esc(name)}</h2><iframe class="video" src="${youtube(url)}" allowfullscreen></iframe>`}
function youtube(u){if(!u)return'';const m=u.match(/shorts\/([^?]+)/)||u.match(/[?&]v=([^&]+)/);return m?`https://www.youtube.com/embed/${m[1]}`:u}
window.onpopstate=()=>home();init();
